name: huckleberryink
favicon: null
layout_spectrum: 0.8199473561253399
typography_spectrum: 0.03144402033649385
title: HuckleberryInk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6057675965130329
  lightness: 0.03689346369355917
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
